namespace SMSManagement.Modules.Coupon.Domain;

/// <summary>
/// A partner brand whose coupons a project distributes (Lotus's, Central,
/// Starbucks, …). Per-project so each campaign owns its own brand list and
/// display customisation. The redemption page renders from these fields.
/// </summary>
public sealed class CouponBrand
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid ProjectId { get; set; }

    /// <summary>Canonical lower-case key used in the redeem URL (?brand=lotus).</summary>
    public string Name { get; set; } = string.Empty;
    public string DisplayName { get; set; } = string.Empty;

    /// <summary>Logo shown on the redemption page. Any reachable URL.</summary>
    public string? LogoUrl { get; set; }

    /// <summary>Hex accent colour for the redemption page theme.</summary>
    public string ThemeColor { get; set; } = "#0066cc";

    /// <summary>Free-text / lightweight HTML shown to the customer on redeem.</summary>
    public string? RedemptionInstructions { get; set; }

    /// <summary>Server-side barcode rendering format: "code128" | "qr" | "code39".</summary>
    public string BarcodeFormat { get; set; } = "code128";

    public bool Enabled { get; set; } = true;
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
}

/// <summary>
/// One bulk import of real brand coupon codes. Carries the token-generation
/// config so every coupon in the batch shares the same public-token shape.
/// Counters are denormalised for cheap dashboard reads.
/// </summary>
public sealed class CouponBatch
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid ProjectId { get; set; }
    public Guid BrandId { get; set; }

    public string Name { get; set; } = string.Empty;
    public decimal Value { get; set; }
    public DateTimeOffset? ExpiresAt { get; set; }

    /// <summary>Length of the generated public token. 4–32.</summary>
    public int TokenLength { get; set; } = 10;

    /// <summary>Alphabet the token is drawn from — ambiguous chars stripped by default.</summary>
    public string TokenAlphabet { get; set; } = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

    public int TotalCount { get; set; }
    public int AllocatedCount { get; set; }
    public int RedeemedCount { get; set; }

    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
    public Guid? CreatedByUserId { get; set; }
}

public enum CouponStatus
{
    /// <summary>Imported, not yet handed to a customer.</summary>
    Available = 0,
    /// <summary>Reserved for a specific workflow instance / customer.</summary>
    Allocated = 1,
    /// <summary>Customer redeemed it — terminal.</summary>
    Redeemed = 2,
    /// <summary>Past its expiry without being redeemed — terminal.</summary>
    Expired = 3,
    /// <summary>Manually voided by an admin — terminal.</summary>
    Void = 4
}

/// <summary>
/// A single coupon. Two codes:
///   Token     — generated by THIS system, unique per project, the public
///               value in the redeem URL. Configurable shape (see CouponBatch).
///   RealCode  — the actual brand coupon code imported from the operator's
///               file. Unique SYSTEM-WIDE (a brand never issues the same code
///               twice); stored encrypted because it carries value, with a
///               hash alongside for the global duplicate check.
/// One coupon is allocated to exactly one customer (one WorkflowInstance).
/// </summary>
public sealed class Coupon
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid ProjectId { get; set; }
    public Guid BatchId { get; set; }
    public Guid BrandId { get; set; }

    /// <summary>System-generated public token (unique per project).</summary>
    public string Token { get; set; } = string.Empty;

    /// <summary>AES-GCM ciphertext of the real brand coupon code.</summary>
    public byte[] EncryptedRealCode { get; set; } = Array.Empty<byte>();

    /// <summary>SHA-256 hex of the trimmed real code — unique index enforces
    /// system-wide dedup without exposing the plaintext.</summary>
    public string RealCodeHash { get; set; } = string.Empty;

    public decimal Value { get; set; }
    public DateTimeOffset? ExpiresAt { get; set; }
    public CouponStatus Status { get; set; } = CouponStatus.Available;

    /// <summary>The campaign send that allocated this coupon, if any.</summary>
    public Guid? WorkflowInstanceId { get; set; }

    public DateTimeOffset? AllocatedAt { get; set; }
    public DateTimeOffset? RedeemedAt { get; set; }
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
}

/// <summary>Audit row written the moment a coupon is redeemed — one per coupon
/// (the conditional UPDATE guarantees a single successful redemption).</summary>
public sealed class CouponRedemption
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid CouponId { get; set; }
    public DateTimeOffset RedeemedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>Salted hash of the redeemer IP — never the raw address.</summary>
    public string? IpHash { get; set; }
    public string? UserAgent { get; set; }
}
